// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ModelTranformation.proto

package cn.tera.protobuf.model;

public final class ModelTransformation {
  private ModelTransformation() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PersonOrBuilder extends
      // @@protoc_insertion_point(interface_extends:tutorial.Person)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>int32 id = 2;</code>
     * @return The id.
     */
    int getId();

    /**
     * <code>string email = 3;</code>
     * @return The email.
     */
    java.lang.String getEmail();
    /**
     * <code>string email = 3;</code>
     * @return The bytes for email.
     */
    com.google.protobuf.ByteString
        getEmailBytes();

    /**
     * <code>repeated string contacts = 4;</code>
     * @return A list containing the contacts.
     */
    java.util.List<java.lang.String>
        getContactsList();
    /**
     * <code>repeated string contacts = 4;</code>
     * @return The count of contacts.
     */
    int getContactsCount();
    /**
     * <code>repeated string contacts = 4;</code>
     * @param index The index of the element to return.
     * @return The contacts at the given index.
     */
    java.lang.String getContacts(int index);
    /**
     * <code>repeated string contacts = 4;</code>
     * @param index The index of the value to return.
     * @return The bytes of the contacts at the given index.
     */
    com.google.protobuf.ByteString
        getContactsBytes(int index);
  }
  /**
   * Protobuf type {@code tutorial.Person}
   */
  public  static final class Person extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:tutorial.Person)
      PersonOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Person.newBuilder() to construct.
    private Person(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Person() {
      name_ = "";
      email_ = "";
      contacts_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Person();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Person(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 16: {

              id_ = input.readInt32();
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              email_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                contacts_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000001;
              }
              contacts_.add(s);
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          contacts_ = contacts_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.tera.protobuf.model.ModelTransformation.internal_static_tutorial_Person_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.tera.protobuf.model.ModelTransformation.internal_static_tutorial_Person_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cn.tera.protobuf.model.ModelTransformation.Person.class, cn.tera.protobuf.model.ModelTransformation.Person.Builder.class);
    }

    public static final int NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ID_FIELD_NUMBER = 2;
    private int id_;
    /**
     * <code>int32 id = 2;</code>
     * @return The id.
     */
    public int getId() {
      return id_;
    }

    public static final int EMAIL_FIELD_NUMBER = 3;
    private volatile java.lang.Object email_;
    /**
     * <code>string email = 3;</code>
     * @return The email.
     */
    public java.lang.String getEmail() {
      java.lang.Object ref = email_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        email_ = s;
        return s;
      }
    }
    /**
     * <code>string email = 3;</code>
     * @return The bytes for email.
     */
    public com.google.protobuf.ByteString
        getEmailBytes() {
      java.lang.Object ref = email_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        email_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CONTACTS_FIELD_NUMBER = 4;
    private com.google.protobuf.LazyStringList contacts_;
    /**
     * <code>repeated string contacts = 4;</code>
     * @return A list containing the contacts.
     */
    public com.google.protobuf.ProtocolStringList
        getContactsList() {
      return contacts_;
    }
    /**
     * <code>repeated string contacts = 4;</code>
     * @return The count of contacts.
     */
    public int getContactsCount() {
      return contacts_.size();
    }
    /**
     * <code>repeated string contacts = 4;</code>
     * @param index The index of the element to return.
     * @return The contacts at the given index.
     */
    public java.lang.String getContacts(int index) {
      return contacts_.get(index);
    }
    /**
     * <code>repeated string contacts = 4;</code>
     * @param index The index of the value to return.
     * @return The bytes of the contacts at the given index.
     */
    public com.google.protobuf.ByteString
        getContactsBytes(int index) {
      return contacts_.getByteString(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
      if (id_ != 0) {
        output.writeInt32(2, id_);
      }
      if (!getEmailBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, email_);
      }
      for (int i = 0; i < contacts_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, contacts_.getRaw(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, id_);
      }
      if (!getEmailBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, email_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < contacts_.size(); i++) {
          dataSize += computeStringSizeNoTag(contacts_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getContactsList().size();
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cn.tera.protobuf.model.ModelTransformation.Person)) {
        return super.equals(obj);
      }
      cn.tera.protobuf.model.ModelTransformation.Person other = (cn.tera.protobuf.model.ModelTransformation.Person) obj;

      if (!getName()
          .equals(other.getName())) return false;
      if (getId()
          != other.getId()) return false;
      if (!getEmail()
          .equals(other.getEmail())) return false;
      if (!getContactsList()
          .equals(other.getContactsList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + EMAIL_FIELD_NUMBER;
      hash = (53 * hash) + getEmail().hashCode();
      if (getContactsCount() > 0) {
        hash = (37 * hash) + CONTACTS_FIELD_NUMBER;
        hash = (53 * hash) + getContactsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cn.tera.protobuf.model.ModelTransformation.Person parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.tera.protobuf.model.ModelTransformation.Person parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.tera.protobuf.model.ModelTransformation.Person parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.tera.protobuf.model.ModelTransformation.Person parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.tera.protobuf.model.ModelTransformation.Person parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.tera.protobuf.model.ModelTransformation.Person parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.tera.protobuf.model.ModelTransformation.Person parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.tera.protobuf.model.ModelTransformation.Person parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.tera.protobuf.model.ModelTransformation.Person parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static cn.tera.protobuf.model.ModelTransformation.Person parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.tera.protobuf.model.ModelTransformation.Person parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.tera.protobuf.model.ModelTransformation.Person parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cn.tera.protobuf.model.ModelTransformation.Person prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code tutorial.Person}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:tutorial.Person)
        cn.tera.protobuf.model.ModelTransformation.PersonOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cn.tera.protobuf.model.ModelTransformation.internal_static_tutorial_Person_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cn.tera.protobuf.model.ModelTransformation.internal_static_tutorial_Person_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cn.tera.protobuf.model.ModelTransformation.Person.class, cn.tera.protobuf.model.ModelTransformation.Person.Builder.class);
      }

      // Construct using cn.tera.protobuf.model.ModelTransformation.Person.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        name_ = "";

        id_ = 0;

        email_ = "";

        contacts_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cn.tera.protobuf.model.ModelTransformation.internal_static_tutorial_Person_descriptor;
      }

      @java.lang.Override
      public cn.tera.protobuf.model.ModelTransformation.Person getDefaultInstanceForType() {
        return cn.tera.protobuf.model.ModelTransformation.Person.getDefaultInstance();
      }

      @java.lang.Override
      public cn.tera.protobuf.model.ModelTransformation.Person build() {
        cn.tera.protobuf.model.ModelTransformation.Person result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public cn.tera.protobuf.model.ModelTransformation.Person buildPartial() {
        cn.tera.protobuf.model.ModelTransformation.Person result = new cn.tera.protobuf.model.ModelTransformation.Person(this);
        int from_bitField0_ = bitField0_;
        result.name_ = name_;
        result.id_ = id_;
        result.email_ = email_;
        if (((bitField0_ & 0x00000001) != 0)) {
          contacts_ = contacts_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.contacts_ = contacts_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cn.tera.protobuf.model.ModelTransformation.Person) {
          return mergeFrom((cn.tera.protobuf.model.ModelTransformation.Person)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cn.tera.protobuf.model.ModelTransformation.Person other) {
        if (other == cn.tera.protobuf.model.ModelTransformation.Person.getDefaultInstance()) return this;
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (!other.getEmail().isEmpty()) {
          email_ = other.email_;
          onChanged();
        }
        if (!other.contacts_.isEmpty()) {
          if (contacts_.isEmpty()) {
            contacts_ = other.contacts_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureContactsIsMutable();
            contacts_.addAll(other.contacts_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cn.tera.protobuf.model.ModelTransformation.Person parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cn.tera.protobuf.model.ModelTransformation.Person) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 1;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private int id_ ;
      /**
       * <code>int32 id = 2;</code>
       * @return The id.
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 2;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object email_ = "";
      /**
       * <code>string email = 3;</code>
       * @return The email.
       */
      public java.lang.String getEmail() {
        java.lang.Object ref = email_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          email_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string email = 3;</code>
       * @return The bytes for email.
       */
      public com.google.protobuf.ByteString
          getEmailBytes() {
        java.lang.Object ref = email_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          email_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string email = 3;</code>
       * @param value The email to set.
       * @return This builder for chaining.
       */
      public Builder setEmail(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        email_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string email = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearEmail() {
        
        email_ = getDefaultInstance().getEmail();
        onChanged();
        return this;
      }
      /**
       * <code>string email = 3;</code>
       * @param value The bytes for email to set.
       * @return This builder for chaining.
       */
      public Builder setEmailBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        email_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList contacts_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureContactsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          contacts_ = new com.google.protobuf.LazyStringArrayList(contacts_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated string contacts = 4;</code>
       * @return A list containing the contacts.
       */
      public com.google.protobuf.ProtocolStringList
          getContactsList() {
        return contacts_.getUnmodifiableView();
      }
      /**
       * <code>repeated string contacts = 4;</code>
       * @return The count of contacts.
       */
      public int getContactsCount() {
        return contacts_.size();
      }
      /**
       * <code>repeated string contacts = 4;</code>
       * @param index The index of the element to return.
       * @return The contacts at the given index.
       */
      public java.lang.String getContacts(int index) {
        return contacts_.get(index);
      }
      /**
       * <code>repeated string contacts = 4;</code>
       * @param index The index of the value to return.
       * @return The bytes of the contacts at the given index.
       */
      public com.google.protobuf.ByteString
          getContactsBytes(int index) {
        return contacts_.getByteString(index);
      }
      /**
       * <code>repeated string contacts = 4;</code>
       * @param index The index to set the value at.
       * @param value The contacts to set.
       * @return This builder for chaining.
       */
      public Builder setContacts(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureContactsIsMutable();
        contacts_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string contacts = 4;</code>
       * @param value The contacts to add.
       * @return This builder for chaining.
       */
      public Builder addContacts(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureContactsIsMutable();
        contacts_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string contacts = 4;</code>
       * @param values The contacts to add.
       * @return This builder for chaining.
       */
      public Builder addAllContacts(
          java.lang.Iterable<java.lang.String> values) {
        ensureContactsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, contacts_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string contacts = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearContacts() {
        contacts_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string contacts = 4;</code>
       * @param value The bytes of the contacts to add.
       * @return This builder for chaining.
       */
      public Builder addContactsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureContactsIsMutable();
        contacts_.add(value);
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:tutorial.Person)
    }

    // @@protoc_insertion_point(class_scope:tutorial.Person)
    private static final cn.tera.protobuf.model.ModelTransformation.Person DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cn.tera.protobuf.model.ModelTransformation.Person();
    }

    public static cn.tera.protobuf.model.ModelTransformation.Person getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Person>
        PARSER = new com.google.protobuf.AbstractParser<Person>() {
      @java.lang.Override
      public Person parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Person(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Person> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Person> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public cn.tera.protobuf.model.ModelTransformation.Person getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ComputerOrBuilder extends
      // @@protoc_insertion_point(interface_extends:tutorial.Computer)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string type = 1;</code>
     * @return The type.
     */
    java.lang.String getType();
    /**
     * <code>string type = 1;</code>
     * @return The bytes for type.
     */
    com.google.protobuf.ByteString
        getTypeBytes();

    /**
     * <code>int32 cpu = 2;</code>
     * @return The cpu.
     */
    int getCpu();

    /**
     * <code>string merchant = 3;</code>
     * @return The merchant.
     */
    java.lang.String getMerchant();
    /**
     * <code>string merchant = 3;</code>
     * @return The bytes for merchant.
     */
    com.google.protobuf.ByteString
        getMerchantBytes();

    /**
     * <code>repeated string disks = 4;</code>
     * @return A list containing the disks.
     */
    java.util.List<java.lang.String>
        getDisksList();
    /**
     * <code>repeated string disks = 4;</code>
     * @return The count of disks.
     */
    int getDisksCount();
    /**
     * <code>repeated string disks = 4;</code>
     * @param index The index of the element to return.
     * @return The disks at the given index.
     */
    java.lang.String getDisks(int index);
    /**
     * <code>repeated string disks = 4;</code>
     * @param index The index of the value to return.
     * @return The bytes of the disks at the given index.
     */
    com.google.protobuf.ByteString
        getDisksBytes(int index);
  }
  /**
   * Protobuf type {@code tutorial.Computer}
   */
  public  static final class Computer extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:tutorial.Computer)
      ComputerOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Computer.newBuilder() to construct.
    private Computer(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Computer() {
      type_ = "";
      merchant_ = "";
      disks_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Computer();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Computer(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              type_ = s;
              break;
            }
            case 16: {

              cpu_ = input.readInt32();
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              merchant_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                disks_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000001;
              }
              disks_.add(s);
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          disks_ = disks_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.tera.protobuf.model.ModelTransformation.internal_static_tutorial_Computer_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.tera.protobuf.model.ModelTransformation.internal_static_tutorial_Computer_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cn.tera.protobuf.model.ModelTransformation.Computer.class, cn.tera.protobuf.model.ModelTransformation.Computer.Builder.class);
    }

    public static final int TYPE_FIELD_NUMBER = 1;
    private volatile java.lang.Object type_;
    /**
     * <code>string type = 1;</code>
     * @return The type.
     */
    public java.lang.String getType() {
      java.lang.Object ref = type_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        type_ = s;
        return s;
      }
    }
    /**
     * <code>string type = 1;</code>
     * @return The bytes for type.
     */
    public com.google.protobuf.ByteString
        getTypeBytes() {
      java.lang.Object ref = type_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        type_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CPU_FIELD_NUMBER = 2;
    private int cpu_;
    /**
     * <code>int32 cpu = 2;</code>
     * @return The cpu.
     */
    public int getCpu() {
      return cpu_;
    }

    public static final int MERCHANT_FIELD_NUMBER = 3;
    private volatile java.lang.Object merchant_;
    /**
     * <code>string merchant = 3;</code>
     * @return The merchant.
     */
    public java.lang.String getMerchant() {
      java.lang.Object ref = merchant_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        merchant_ = s;
        return s;
      }
    }
    /**
     * <code>string merchant = 3;</code>
     * @return The bytes for merchant.
     */
    public com.google.protobuf.ByteString
        getMerchantBytes() {
      java.lang.Object ref = merchant_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        merchant_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DISKS_FIELD_NUMBER = 4;
    private com.google.protobuf.LazyStringList disks_;
    /**
     * <code>repeated string disks = 4;</code>
     * @return A list containing the disks.
     */
    public com.google.protobuf.ProtocolStringList
        getDisksList() {
      return disks_;
    }
    /**
     * <code>repeated string disks = 4;</code>
     * @return The count of disks.
     */
    public int getDisksCount() {
      return disks_.size();
    }
    /**
     * <code>repeated string disks = 4;</code>
     * @param index The index of the element to return.
     * @return The disks at the given index.
     */
    public java.lang.String getDisks(int index) {
      return disks_.get(index);
    }
    /**
     * <code>repeated string disks = 4;</code>
     * @param index The index of the value to return.
     * @return The bytes of the disks at the given index.
     */
    public com.google.protobuf.ByteString
        getDisksBytes(int index) {
      return disks_.getByteString(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getTypeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, type_);
      }
      if (cpu_ != 0) {
        output.writeInt32(2, cpu_);
      }
      if (!getMerchantBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, merchant_);
      }
      for (int i = 0; i < disks_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, disks_.getRaw(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getTypeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, type_);
      }
      if (cpu_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, cpu_);
      }
      if (!getMerchantBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, merchant_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < disks_.size(); i++) {
          dataSize += computeStringSizeNoTag(disks_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getDisksList().size();
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cn.tera.protobuf.model.ModelTransformation.Computer)) {
        return super.equals(obj);
      }
      cn.tera.protobuf.model.ModelTransformation.Computer other = (cn.tera.protobuf.model.ModelTransformation.Computer) obj;

      if (!getType()
          .equals(other.getType())) return false;
      if (getCpu()
          != other.getCpu()) return false;
      if (!getMerchant()
          .equals(other.getMerchant())) return false;
      if (!getDisksList()
          .equals(other.getDisksList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getType().hashCode();
      hash = (37 * hash) + CPU_FIELD_NUMBER;
      hash = (53 * hash) + getCpu();
      hash = (37 * hash) + MERCHANT_FIELD_NUMBER;
      hash = (53 * hash) + getMerchant().hashCode();
      if (getDisksCount() > 0) {
        hash = (37 * hash) + DISKS_FIELD_NUMBER;
        hash = (53 * hash) + getDisksList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cn.tera.protobuf.model.ModelTransformation.Computer parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.tera.protobuf.model.ModelTransformation.Computer parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.tera.protobuf.model.ModelTransformation.Computer parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.tera.protobuf.model.ModelTransformation.Computer parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.tera.protobuf.model.ModelTransformation.Computer parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.tera.protobuf.model.ModelTransformation.Computer parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.tera.protobuf.model.ModelTransformation.Computer parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.tera.protobuf.model.ModelTransformation.Computer parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.tera.protobuf.model.ModelTransformation.Computer parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static cn.tera.protobuf.model.ModelTransformation.Computer parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.tera.protobuf.model.ModelTransformation.Computer parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.tera.protobuf.model.ModelTransformation.Computer parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cn.tera.protobuf.model.ModelTransformation.Computer prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code tutorial.Computer}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:tutorial.Computer)
        cn.tera.protobuf.model.ModelTransformation.ComputerOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cn.tera.protobuf.model.ModelTransformation.internal_static_tutorial_Computer_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cn.tera.protobuf.model.ModelTransformation.internal_static_tutorial_Computer_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cn.tera.protobuf.model.ModelTransformation.Computer.class, cn.tera.protobuf.model.ModelTransformation.Computer.Builder.class);
      }

      // Construct using cn.tera.protobuf.model.ModelTransformation.Computer.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        type_ = "";

        cpu_ = 0;

        merchant_ = "";

        disks_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cn.tera.protobuf.model.ModelTransformation.internal_static_tutorial_Computer_descriptor;
      }

      @java.lang.Override
      public cn.tera.protobuf.model.ModelTransformation.Computer getDefaultInstanceForType() {
        return cn.tera.protobuf.model.ModelTransformation.Computer.getDefaultInstance();
      }

      @java.lang.Override
      public cn.tera.protobuf.model.ModelTransformation.Computer build() {
        cn.tera.protobuf.model.ModelTransformation.Computer result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public cn.tera.protobuf.model.ModelTransformation.Computer buildPartial() {
        cn.tera.protobuf.model.ModelTransformation.Computer result = new cn.tera.protobuf.model.ModelTransformation.Computer(this);
        int from_bitField0_ = bitField0_;
        result.type_ = type_;
        result.cpu_ = cpu_;
        result.merchant_ = merchant_;
        if (((bitField0_ & 0x00000001) != 0)) {
          disks_ = disks_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.disks_ = disks_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cn.tera.protobuf.model.ModelTransformation.Computer) {
          return mergeFrom((cn.tera.protobuf.model.ModelTransformation.Computer)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cn.tera.protobuf.model.ModelTransformation.Computer other) {
        if (other == cn.tera.protobuf.model.ModelTransformation.Computer.getDefaultInstance()) return this;
        if (!other.getType().isEmpty()) {
          type_ = other.type_;
          onChanged();
        }
        if (other.getCpu() != 0) {
          setCpu(other.getCpu());
        }
        if (!other.getMerchant().isEmpty()) {
          merchant_ = other.merchant_;
          onChanged();
        }
        if (!other.disks_.isEmpty()) {
          if (disks_.isEmpty()) {
            disks_ = other.disks_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureDisksIsMutable();
            disks_.addAll(other.disks_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cn.tera.protobuf.model.ModelTransformation.Computer parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cn.tera.protobuf.model.ModelTransformation.Computer) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object type_ = "";
      /**
       * <code>string type = 1;</code>
       * @return The type.
       */
      public java.lang.String getType() {
        java.lang.Object ref = type_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          type_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string type = 1;</code>
       * @return The bytes for type.
       */
      public com.google.protobuf.ByteString
          getTypeBytes() {
        java.lang.Object ref = type_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          type_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string type = 1;</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string type = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        
        type_ = getDefaultInstance().getType();
        onChanged();
        return this;
      }
      /**
       * <code>string type = 1;</code>
       * @param value The bytes for type to set.
       * @return This builder for chaining.
       */
      public Builder setTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        type_ = value;
        onChanged();
        return this;
      }

      private int cpu_ ;
      /**
       * <code>int32 cpu = 2;</code>
       * @return The cpu.
       */
      public int getCpu() {
        return cpu_;
      }
      /**
       * <code>int32 cpu = 2;</code>
       * @param value The cpu to set.
       * @return This builder for chaining.
       */
      public Builder setCpu(int value) {
        
        cpu_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 cpu = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearCpu() {
        
        cpu_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object merchant_ = "";
      /**
       * <code>string merchant = 3;</code>
       * @return The merchant.
       */
      public java.lang.String getMerchant() {
        java.lang.Object ref = merchant_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          merchant_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string merchant = 3;</code>
       * @return The bytes for merchant.
       */
      public com.google.protobuf.ByteString
          getMerchantBytes() {
        java.lang.Object ref = merchant_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          merchant_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string merchant = 3;</code>
       * @param value The merchant to set.
       * @return This builder for chaining.
       */
      public Builder setMerchant(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        merchant_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string merchant = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearMerchant() {
        
        merchant_ = getDefaultInstance().getMerchant();
        onChanged();
        return this;
      }
      /**
       * <code>string merchant = 3;</code>
       * @param value The bytes for merchant to set.
       * @return This builder for chaining.
       */
      public Builder setMerchantBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        merchant_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList disks_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureDisksIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          disks_ = new com.google.protobuf.LazyStringArrayList(disks_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated string disks = 4;</code>
       * @return A list containing the disks.
       */
      public com.google.protobuf.ProtocolStringList
          getDisksList() {
        return disks_.getUnmodifiableView();
      }
      /**
       * <code>repeated string disks = 4;</code>
       * @return The count of disks.
       */
      public int getDisksCount() {
        return disks_.size();
      }
      /**
       * <code>repeated string disks = 4;</code>
       * @param index The index of the element to return.
       * @return The disks at the given index.
       */
      public java.lang.String getDisks(int index) {
        return disks_.get(index);
      }
      /**
       * <code>repeated string disks = 4;</code>
       * @param index The index of the value to return.
       * @return The bytes of the disks at the given index.
       */
      public com.google.protobuf.ByteString
          getDisksBytes(int index) {
        return disks_.getByteString(index);
      }
      /**
       * <code>repeated string disks = 4;</code>
       * @param index The index to set the value at.
       * @param value The disks to set.
       * @return This builder for chaining.
       */
      public Builder setDisks(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureDisksIsMutable();
        disks_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string disks = 4;</code>
       * @param value The disks to add.
       * @return This builder for chaining.
       */
      public Builder addDisks(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureDisksIsMutable();
        disks_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string disks = 4;</code>
       * @param values The disks to add.
       * @return This builder for chaining.
       */
      public Builder addAllDisks(
          java.lang.Iterable<java.lang.String> values) {
        ensureDisksIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, disks_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string disks = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearDisks() {
        disks_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string disks = 4;</code>
       * @param value The bytes of the disks to add.
       * @return This builder for chaining.
       */
      public Builder addDisksBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureDisksIsMutable();
        disks_.add(value);
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:tutorial.Computer)
    }

    // @@protoc_insertion_point(class_scope:tutorial.Computer)
    private static final cn.tera.protobuf.model.ModelTransformation.Computer DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cn.tera.protobuf.model.ModelTransformation.Computer();
    }

    public static cn.tera.protobuf.model.ModelTransformation.Computer getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Computer>
        PARSER = new com.google.protobuf.AbstractParser<Computer>() {
      @java.lang.Override
      public Computer parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Computer(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Computer> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Computer> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public cn.tera.protobuf.model.ModelTransformation.Computer getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_Person_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tutorial_Person_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_Computer_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tutorial_Computer_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030ModelTranformation.proto\022\010tutorial\"C\n\006" +
      "Person\022\014\n\004name\030\001 \001(\t\022\n\n\002id\030\002 \001(\005\022\r\n\005emai" +
      "l\030\003 \001(\t\022\020\n\010contacts\030\004 \003(\t\"F\n\010Computer\022\014\n" +
      "\004type\030\001 \001(\t\022\013\n\003cpu\030\002 \001(\005\022\020\n\010merchant\030\003 \001" +
      "(\t\022\r\n\005disks\030\004 \003(\tB-\n\026cn.tera.protobuf.mo" +
      "delB\023ModelTransformationb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_tutorial_Person_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_tutorial_Person_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tutorial_Person_descriptor,
        new java.lang.String[] { "Name", "Id", "Email", "Contacts", });
    internal_static_tutorial_Computer_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_tutorial_Computer_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tutorial_Computer_descriptor,
        new java.lang.String[] { "Type", "Cpu", "Merchant", "Disks", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
