// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package cn.tera.protobuf.coder.models.protobuf;

public final class ProtobufStudent {
  private ProtobufStudent() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface StudentOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Student)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 age = 1;</code>
     * @return The age.
     */
    int getAge();

    /**
     * <code>int64 hairCount = 2;</code>
     * @return The hairCount.
     */
    long getHairCount();

    /**
     * <code>bool isMale = 3;</code>
     * @return The isMale.
     */
    boolean getIsMale();

    /**
     * <code>string name = 4;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>string name = 4;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>double score = 5;</code>
     * @return The score.
     */
    double getScore();

    /**
     * <code>float score2 = 6;</code>
     * @return The score2.
     */
    float getScore2();

    /**
     * <code>string tag = 23;</code>
     * @return The tag.
     */
    java.lang.String getTag();
    /**
     * <code>string tag = 23;</code>
     * @return The bytes for tag.
     */
    com.google.protobuf.ByteString
        getTagBytes();
  }
  /**
   * Protobuf type {@code Student}
   */
  public  static final class Student extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Student)
      StudentOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Student.newBuilder() to construct.
    private Student(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Student() {
      name_ = "";
      tag_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Student();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Student(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              age_ = input.readInt32();
              break;
            }
            case 16: {

              hairCount_ = input.readInt64();
              break;
            }
            case 24: {

              isMale_ = input.readBool();
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 41: {

              score_ = input.readDouble();
              break;
            }
            case 53: {

              score2_ = input.readFloat();
              break;
            }
            case 186: {
              java.lang.String s = input.readStringRequireUtf8();

              tag_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.tera.protobuf.coder.models.protobuf.ProtobufStudent.internal_static_Student_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.tera.protobuf.coder.models.protobuf.ProtobufStudent.internal_static_Student_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cn.tera.protobuf.coder.models.protobuf.ProtobufStudent.Student.class, cn.tera.protobuf.coder.models.protobuf.ProtobufStudent.Student.Builder.class);
    }

    public static final int AGE_FIELD_NUMBER = 1;
    private int age_;
    /**
     * <code>int32 age = 1;</code>
     * @return The age.
     */
    public int getAge() {
      return age_;
    }

    public static final int HAIRCOUNT_FIELD_NUMBER = 2;
    private long hairCount_;
    /**
     * <code>int64 hairCount = 2;</code>
     * @return The hairCount.
     */
    public long getHairCount() {
      return hairCount_;
    }

    public static final int ISMALE_FIELD_NUMBER = 3;
    private boolean isMale_;
    /**
     * <code>bool isMale = 3;</code>
     * @return The isMale.
     */
    public boolean getIsMale() {
      return isMale_;
    }

    public static final int NAME_FIELD_NUMBER = 4;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 4;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 4;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SCORE_FIELD_NUMBER = 5;
    private double score_;
    /**
     * <code>double score = 5;</code>
     * @return The score.
     */
    public double getScore() {
      return score_;
    }

    public static final int SCORE2_FIELD_NUMBER = 6;
    private float score2_;
    /**
     * <code>float score2 = 6;</code>
     * @return The score2.
     */
    public float getScore2() {
      return score2_;
    }

    public static final int TAG_FIELD_NUMBER = 23;
    private volatile java.lang.Object tag_;
    /**
     * <code>string tag = 23;</code>
     * @return The tag.
     */
    public java.lang.String getTag() {
      java.lang.Object ref = tag_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        tag_ = s;
        return s;
      }
    }
    /**
     * <code>string tag = 23;</code>
     * @return The bytes for tag.
     */
    public com.google.protobuf.ByteString
        getTagBytes() {
      java.lang.Object ref = tag_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tag_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (age_ != 0) {
        output.writeInt32(1, age_);
      }
      if (hairCount_ != 0L) {
        output.writeInt64(2, hairCount_);
      }
      if (isMale_ != false) {
        output.writeBool(3, isMale_);
      }
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, name_);
      }
      if (score_ != 0D) {
        output.writeDouble(5, score_);
      }
      if (score2_ != 0F) {
        output.writeFloat(6, score2_);
      }
      if (!getTagBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 23, tag_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (age_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, age_);
      }
      if (hairCount_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, hairCount_);
      }
      if (isMale_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, isMale_);
      }
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, name_);
      }
      if (score_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(5, score_);
      }
      if (score2_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(6, score2_);
      }
      if (!getTagBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(23, tag_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cn.tera.protobuf.coder.models.protobuf.ProtobufStudent.Student)) {
        return super.equals(obj);
      }
      cn.tera.protobuf.coder.models.protobuf.ProtobufStudent.Student other = (cn.tera.protobuf.coder.models.protobuf.ProtobufStudent.Student) obj;

      if (getAge()
          != other.getAge()) return false;
      if (getHairCount()
          != other.getHairCount()) return false;
      if (getIsMale()
          != other.getIsMale()) return false;
      if (!getName()
          .equals(other.getName())) return false;
      if (java.lang.Double.doubleToLongBits(getScore())
          != java.lang.Double.doubleToLongBits(
              other.getScore())) return false;
      if (java.lang.Float.floatToIntBits(getScore2())
          != java.lang.Float.floatToIntBits(
              other.getScore2())) return false;
      if (!getTag()
          .equals(other.getTag())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + AGE_FIELD_NUMBER;
      hash = (53 * hash) + getAge();
      hash = (37 * hash) + HAIRCOUNT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getHairCount());
      hash = (37 * hash) + ISMALE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIsMale());
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + SCORE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getScore()));
      hash = (37 * hash) + SCORE2_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getScore2());
      hash = (37 * hash) + TAG_FIELD_NUMBER;
      hash = (53 * hash) + getTag().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cn.tera.protobuf.coder.models.protobuf.ProtobufStudent.Student parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.tera.protobuf.coder.models.protobuf.ProtobufStudent.Student parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.tera.protobuf.coder.models.protobuf.ProtobufStudent.Student parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.tera.protobuf.coder.models.protobuf.ProtobufStudent.Student parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.tera.protobuf.coder.models.protobuf.ProtobufStudent.Student parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.tera.protobuf.coder.models.protobuf.ProtobufStudent.Student parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.tera.protobuf.coder.models.protobuf.ProtobufStudent.Student parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.tera.protobuf.coder.models.protobuf.ProtobufStudent.Student parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.tera.protobuf.coder.models.protobuf.ProtobufStudent.Student parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static cn.tera.protobuf.coder.models.protobuf.ProtobufStudent.Student parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.tera.protobuf.coder.models.protobuf.ProtobufStudent.Student parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.tera.protobuf.coder.models.protobuf.ProtobufStudent.Student parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cn.tera.protobuf.coder.models.protobuf.ProtobufStudent.Student prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Student}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Student)
        cn.tera.protobuf.coder.models.protobuf.ProtobufStudent.StudentOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cn.tera.protobuf.coder.models.protobuf.ProtobufStudent.internal_static_Student_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cn.tera.protobuf.coder.models.protobuf.ProtobufStudent.internal_static_Student_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cn.tera.protobuf.coder.models.protobuf.ProtobufStudent.Student.class, cn.tera.protobuf.coder.models.protobuf.ProtobufStudent.Student.Builder.class);
      }

      // Construct using cn.tera.protobuf.coder.models.protobuf.ProtobufStudent.Student.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        age_ = 0;

        hairCount_ = 0L;

        isMale_ = false;

        name_ = "";

        score_ = 0D;

        score2_ = 0F;

        tag_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cn.tera.protobuf.coder.models.protobuf.ProtobufStudent.internal_static_Student_descriptor;
      }

      @java.lang.Override
      public cn.tera.protobuf.coder.models.protobuf.ProtobufStudent.Student getDefaultInstanceForType() {
        return cn.tera.protobuf.coder.models.protobuf.ProtobufStudent.Student.getDefaultInstance();
      }

      @java.lang.Override
      public cn.tera.protobuf.coder.models.protobuf.ProtobufStudent.Student build() {
        cn.tera.protobuf.coder.models.protobuf.ProtobufStudent.Student result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public cn.tera.protobuf.coder.models.protobuf.ProtobufStudent.Student buildPartial() {
        cn.tera.protobuf.coder.models.protobuf.ProtobufStudent.Student result = new cn.tera.protobuf.coder.models.protobuf.ProtobufStudent.Student(this);
        result.age_ = age_;
        result.hairCount_ = hairCount_;
        result.isMale_ = isMale_;
        result.name_ = name_;
        result.score_ = score_;
        result.score2_ = score2_;
        result.tag_ = tag_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cn.tera.protobuf.coder.models.protobuf.ProtobufStudent.Student) {
          return mergeFrom((cn.tera.protobuf.coder.models.protobuf.ProtobufStudent.Student)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cn.tera.protobuf.coder.models.protobuf.ProtobufStudent.Student other) {
        if (other == cn.tera.protobuf.coder.models.protobuf.ProtobufStudent.Student.getDefaultInstance()) return this;
        if (other.getAge() != 0) {
          setAge(other.getAge());
        }
        if (other.getHairCount() != 0L) {
          setHairCount(other.getHairCount());
        }
        if (other.getIsMale() != false) {
          setIsMale(other.getIsMale());
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (other.getScore() != 0D) {
          setScore(other.getScore());
        }
        if (other.getScore2() != 0F) {
          setScore2(other.getScore2());
        }
        if (!other.getTag().isEmpty()) {
          tag_ = other.tag_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cn.tera.protobuf.coder.models.protobuf.ProtobufStudent.Student parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cn.tera.protobuf.coder.models.protobuf.ProtobufStudent.Student) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int age_ ;
      /**
       * <code>int32 age = 1;</code>
       * @return The age.
       */
      public int getAge() {
        return age_;
      }
      /**
       * <code>int32 age = 1;</code>
       * @param value The age to set.
       * @return This builder for chaining.
       */
      public Builder setAge(int value) {
        
        age_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 age = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearAge() {
        
        age_ = 0;
        onChanged();
        return this;
      }

      private long hairCount_ ;
      /**
       * <code>int64 hairCount = 2;</code>
       * @return The hairCount.
       */
      public long getHairCount() {
        return hairCount_;
      }
      /**
       * <code>int64 hairCount = 2;</code>
       * @param value The hairCount to set.
       * @return This builder for chaining.
       */
      public Builder setHairCount(long value) {
        
        hairCount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 hairCount = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearHairCount() {
        
        hairCount_ = 0L;
        onChanged();
        return this;
      }

      private boolean isMale_ ;
      /**
       * <code>bool isMale = 3;</code>
       * @return The isMale.
       */
      public boolean getIsMale() {
        return isMale_;
      }
      /**
       * <code>bool isMale = 3;</code>
       * @param value The isMale to set.
       * @return This builder for chaining.
       */
      public Builder setIsMale(boolean value) {
        
        isMale_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool isMale = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearIsMale() {
        
        isMale_ = false;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 4;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 4;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 4;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 4;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private double score_ ;
      /**
       * <code>double score = 5;</code>
       * @return The score.
       */
      public double getScore() {
        return score_;
      }
      /**
       * <code>double score = 5;</code>
       * @param value The score to set.
       * @return This builder for chaining.
       */
      public Builder setScore(double value) {
        
        score_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double score = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearScore() {
        
        score_ = 0D;
        onChanged();
        return this;
      }

      private float score2_ ;
      /**
       * <code>float score2 = 6;</code>
       * @return The score2.
       */
      public float getScore2() {
        return score2_;
      }
      /**
       * <code>float score2 = 6;</code>
       * @param value The score2 to set.
       * @return This builder for chaining.
       */
      public Builder setScore2(float value) {
        
        score2_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float score2 = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearScore2() {
        
        score2_ = 0F;
        onChanged();
        return this;
      }

      private java.lang.Object tag_ = "";
      /**
       * <code>string tag = 23;</code>
       * @return The tag.
       */
      public java.lang.String getTag() {
        java.lang.Object ref = tag_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          tag_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string tag = 23;</code>
       * @return The bytes for tag.
       */
      public com.google.protobuf.ByteString
          getTagBytes() {
        java.lang.Object ref = tag_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          tag_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string tag = 23;</code>
       * @param value The tag to set.
       * @return This builder for chaining.
       */
      public Builder setTag(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        tag_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string tag = 23;</code>
       * @return This builder for chaining.
       */
      public Builder clearTag() {
        
        tag_ = getDefaultInstance().getTag();
        onChanged();
        return this;
      }
      /**
       * <code>string tag = 23;</code>
       * @param value The bytes for tag to set.
       * @return This builder for chaining.
       */
      public Builder setTagBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        tag_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Student)
    }

    // @@protoc_insertion_point(class_scope:Student)
    private static final cn.tera.protobuf.coder.models.protobuf.ProtobufStudent.Student DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cn.tera.protobuf.coder.models.protobuf.ProtobufStudent.Student();
    }

    public static cn.tera.protobuf.coder.models.protobuf.ProtobufStudent.Student getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Student>
        PARSER = new com.google.protobuf.AbstractParser<Student>() {
      @java.lang.Override
      public Student parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Student(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Student> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Student> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public cn.tera.protobuf.coder.models.protobuf.ProtobufStudent.Student getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Student_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Student_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rStudent.proto\"s\n\007Student\022\013\n\003age\030\001 \001(\005\022" +
      "\021\n\thairCount\030\002 \001(\003\022\016\n\006isMale\030\003 \001(\010\022\014\n\004na" +
      "me\030\004 \001(\t\022\r\n\005score\030\005 \001(\001\022\016\n\006score2\030\006 \001(\002\022" +
      "\013\n\003tag\030\027 \001(\tB9\n&cn.tera.protobuf.coder.m" +
      "odels.protobufB\017ProtobufStudentb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Student_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Student_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Student_descriptor,
        new java.lang.String[] { "Age", "HairCount", "IsMale", "Name", "Score", "Score2", "Tag", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
